export const Config = {
  ENV: process.env.ENV,
  PORT: process.env.PORT,
  DATABASE_NAME: process.env.DATABASE_NAME,
  DATABASE_CONNECTION: process.env.DATABASE_CONNECTION,
  DATABASE_CONNECTION_NAME: process.env.DATABASE_CONNECTION_NAME,
  RESTAURANT_COLLECTION_NAME: process.env.RESTAURANT_COLLECTION_NAME,
  USER_COLLECTION_NAME: process.env.USER_COLLECTION_NAME,
  CUISINE_COLLECTION_NAME: process.env.CUISINE_COLLECTION_NAME,
  AREA_IN_METERS: Number(process.env.AREA_IN_METERS),
};
